warning: in the working copy of '.env.example', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'GOOGLE_LOGIN.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'pom.xml', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/aac/controller/AacUsageController.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/aac/service/AacUsageService.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/account/repository/AccountRepository.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/auth/controller/AuthController.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/auth/dto/OnboardingRequest.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/auth/handler/OAuth2SuccessHandler.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/auth/security/SecurityConfig.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/auth/service/AuthService.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/auth/service/CurrentAccountService.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/auth/service/CustomOidcUserService.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/common/config/DataInitializer.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/common/config/WebConfig.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/common/exception/GlobalExceptionHandler.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/guardian/controller/GuardianController.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/guardian/repository/UserGuardianRepository.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/guardian/service/GuardianService.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/user/controller/UserController.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/user/dto/CreateUserRequest.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/java/com/aac/ieojwo/user/service/UserService.java', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/resources/application-postgres.yml', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main/resources/application.yml', LF will be replaced by CRLF the next time Git touches it
