package com.aac.ieojwo.alert.service;
import com.aac.ieojwo.alert.domain.*;import com.aac.ieojwo.alert.repository.*;import com.aac.ieojwo.common.exception.*;import com.aac.ieojwo.guardian.domain.Guardian;import com.aac.ieojwo.guardian.service.GuardianAccessService;import com.aac.ieojwo.live.LiveEventService;import com.aac.ieojwo.user.domain.*;import com.aac.ieojwo.user.service.AacUserAccessService;import org.springframework.security.oauth2.core.oidc.user.OidcUser;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service @Transactional(readOnly=true)
public class AlertService{
 public record AlertResponse(Long id,AlertType type,String title,String message,Instant occurredAt,Instant acknowledgedAt){public static AlertResponse from(AlertEvent e){return new AlertResponse(e.getId(),e.getAlertType(),e.getTitle(),e.getMessage(),e.getOccurredAt(),e.getAcknowledgedAt());}}
 private final AlertEventRepository alerts;private final NotificationSubscriptionRepository subscriptions;private final GuardianAccessService guardians;private final AacUserAccessService access;private final LiveEventService live;
 public AlertService(AlertEventRepository a,NotificationSubscriptionRepository s,GuardianAccessService g,AacUserAccessService access,LiveEventService live){alerts=a;subscriptions=s;guardians=g;this.access=access;this.live=live;}
 @Transactional public AlertEvent create(AacUser u,AlertType type,String title,String message){AlertEvent e=alerts.save(AlertEvent.create(u,type,title,message));live.publish(u.getId(),"ALERT",AlertResponse.from(e));return e;}
 public List<AlertResponse> list(OidcUser p,Long id,Instant from,Instant to){access.requireAccessibleUser(p,id);return alerts.findAllByUserIdAndOccurredAtBetweenOrderByOccurredAtDesc(id,from,to).stream().map(AlertResponse::from).toList();}
 @Transactional public AlertResponse acknowledge(OidcUser p,Long id,Long alertId){access.requireAccessibleUser(p,id);AlertEvent e=alerts.findById(alertId).orElseThrow(()->new ResourceNotFoundException("알림을 찾을 수 없습니다."));if(!e.getUser().getId().equals(id))throw new ForbiddenException("다른 사용자의 알림입니다.");e.acknowledge();return AlertResponse.from(e);}
 @Transactional public Long subscribe(OidcUser p,String endpoint,String p256dh,String auth){Guardian g=guardians.requireCurrentGuardian(p);NotificationSubscription s=subscriptions.findByEndpoint(endpoint).map(x->{x.update(g,p256dh,auth);return x;}).orElseGet(()->subscriptions.save(NotificationSubscription.create(g,endpoint,p256dh,auth)));return s.getId();}
}
