package com.aac.ieojwo.report.service;
import com.aac.ieojwo.alert.domain.AlertType;import com.aac.ieojwo.alert.repository.AlertEventRepository;import com.aac.ieojwo.board.domain.CardUsageLog;import com.aac.ieojwo.board.repository.CardUsageLogRepository;import com.aac.ieojwo.report.domain.*;import com.aac.ieojwo.report.repository.SensorEventRepository;import com.aac.ieojwo.user.service.AacUserAccessService;import org.springframework.security.oauth2.core.oidc.user.OidcUser;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.io.*;import java.nio.charset.StandardCharsets;import java.time.Instant;import java.util.*;import java.util.stream.Collectors;
@Service @Transactional(readOnly=true)
public class ReportService{
 public record CountItem(Long id,String name,long count){}public record ShareItem(Long id,String name,long count,double percent){}public record SensorItem(SensorEventType type,Double value,String label,Instant recordedAt){}public record ReportResponse(Long aacUserId,Instant from,Instant to,long totalCardActions,long emergencyCount,List<CountItem> topCards,List<ShareItem> categoryShares,List<SensorItem> sensors,List<String> insights){}
 private final CardUsageLogRepository usage;private final AlertEventRepository alerts;private final SensorEventRepository sensors;private final AacUserAccessService access;
 public ReportService(CardUsageLogRepository u,AlertEventRepository a,SensorEventRepository s,AacUserAccessService access){usage=u;alerts=a;sensors=s;this.access=access;}
 public ReportResponse report(OidcUser p,Long id,Instant from,Instant to){access.requireAccessibleUser(p,id);List<CardUsageLog> logs=usage.findAllByUserIdAndOccurredAtBetweenOrderByOccurredAtAsc(id,from,to);Map<Long,List<CardUsageLog>> byCard=logs.stream().collect(Collectors.groupingBy(x->x.getCard().getId()));List<CountItem> top=byCard.values().stream().map(x->new CountItem(x.get(0).getCard().getId(),x.get(0).getCard().getText(),x.size())).sorted(Comparator.comparingLong(CountItem::count).reversed()).limit(5).toList();Map<Long,List<CardUsageLog>> byCategory=logs.stream().collect(Collectors.groupingBy(x->x.getCard().getCategory().getId()));List<ShareItem> shares=byCategory.values().stream().map(x->new ShareItem(x.get(0).getCard().getCategory().getId(),x.get(0).getCard().getCategory().getName(),x.size(),logs.isEmpty()?0:Math.round(x.size()*1000.0/logs.size())/10.0)).sorted(Comparator.comparingLong(ShareItem::count).reversed()).toList();long emergency=alerts.findAllByUserIdAndOccurredAtBetweenOrderByOccurredAtDesc(id,from,to).stream().filter(x->x.getAlertType()==AlertType.EMERGENCY).count();List<SensorItem> sensorItems=sensors.findAllByUserIdAndRecordedAtBetweenOrderByRecordedAtAsc(id,from,to).stream().map(x->new SensorItem(x.getEventType(),x.getNumericValue(),x.getLabel(),x.getRecordedAt())).toList();List<String> insights=new ArrayList<>();if(!top.isEmpty())insights.add("가장 자주 사용한 카드는 '"+top.get(0).name()+"'이며 "+top.get(0).count()+"회 사용했습니다.");long high=sensorItems.stream().filter(x->x.type()==SensorEventType.HEART_RATE&&x.value()!=null&&x.value()>=110).count();if(high>0)insights.add("110 BPM 이상 고심박 이벤트가 "+high+"회 관측되었습니다.");if(emergency>0)insights.add("긴급 모드가 "+emergency+"회 발생했습니다.");return new ReportResponse(id,from,to,logs.size(),emergency,top,shares,sensorItems,insights);}
 public byte[] pdf(ReportResponse r){List<String> lines=new ArrayList<>();lines.add("Malmoa Guardian Report");lines.add("AAC user: "+r.aacUserId());lines.add("Period: "+r.from()+" - "+r.to());lines.add("Card actions: "+r.totalCardActions());lines.add("Emergency events: "+r.emergencyCount());for(CountItem x:r.topCards())lines.add("Top card #"+x.id()+": "+ascii(x.name())+" ("+x.count()+")");StringBuilder content=new StringBuilder("BT /F1 12 Tf 50 790 Td ");for(String line:lines)content.append("(").append(escape(line)).append(") Tj 0 -20 Td ");content.append("ET");try{ByteArrayOutputStream out=new ByteArrayOutputStream();List<Integer> offsets=new ArrayList<>();write(out,"%PDF-1.4\n");String[] objects={"1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj\n","2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj\n","3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >> endobj\n","4 0 obj << /Length "+content.length()+" >> stream\n"+content+"\nendstream endobj\n","5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj\n"};for(String o:objects){offsets.add(out.size());write(out,o);}int xref=out.size();write(out,"xref\n0 6\n0000000000 65535 f \n");for(int o:offsets)write(out,String.format("%010d 00000 n \n",o));write(out,"trailer << /Size 6 /Root 1 0 R >>\nstartxref\n"+xref+"\n%%EOF");return out.toByteArray();}catch(IOException e){throw new IllegalStateException(e);}}
 private static void write(OutputStream o,String s)throws IOException{o.write(s.getBytes(StandardCharsets.US_ASCII));}private static String ascii(String s){return s.chars().mapToObj(c->c>=32&&c<127?String.valueOf((char)c):"?").collect(Collectors.joining());}private static String escape(String s){return s.replace("\\","\\\\").replace("(","\\(").replace(")","\\)");}
}
