package com.aac.ieojwo.location.service;
import com.aac.ieojwo.alert.domain.AlertType;import com.aac.ieojwo.alert.service.AlertService;import com.aac.ieojwo.common.exception.*;import com.aac.ieojwo.device.domain.AacDevice;import com.aac.ieojwo.live.LiveEventService;import com.aac.ieojwo.location.domain.*;import com.aac.ieojwo.location.repository.*;import com.aac.ieojwo.user.domain.AacUser;import com.aac.ieojwo.user.service.AacUserAccessService;import org.springframework.security.oauth2.core.oidc.user.OidcUser;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service @Transactional(readOnly=true)
public class LocationService{
 public record PlaceRequest(String name,PlaceType placeType,String address,double latitude,double longitude,int radiusMeters,LocalTime activeFrom,LocalTime activeTo){}public record PlaceResponse(Long id,String name,PlaceType placeType,String address,double latitude,double longitude,int radiusMeters,LocalTime activeFrom,LocalTime activeTo){static PlaceResponse from(SavedPlace p){return new PlaceResponse(p.getId(),p.getName(),p.getPlaceType(),p.getAddress(),p.getLatitude(),p.getLongitude(),p.getRadiusMeters(),p.getActiveFrom(),p.getActiveTo());}}public record LocationRequest(double latitude,double longitude,Double accuracyMeters,Instant recordedAt){}public record LocationResponse(Long id,double latitude,double longitude,Double accuracyMeters,Instant recordedAt,List<Long> outsidePlaceIds){static LocationResponse from(LocationSample s,List<Long> o){return new LocationResponse(s.getId(),s.getLatitude(),s.getLongitude(),s.getAccuracyMeters(),s.getRecordedAt(),o);}}
 private final SavedPlaceRepository places;private final LocationSampleRepository samples;private final AacUserAccessService access;private final AlertService alerts;private final LiveEventService live;
 public LocationService(SavedPlaceRepository p,LocationSampleRepository s,AacUserAccessService a,AlertService alerts,LiveEventService live){places=p;samples=s;access=a;this.alerts=alerts;this.live=live;}
 public List<PlaceResponse> places(OidcUser p,Long id){access.requireAccessibleUser(p,id);return places.findAllByUserIdAndActiveTrueOrderByIdAsc(id).stream().map(PlaceResponse::from).toList();}
 @Transactional public PlaceResponse save(OidcUser p,Long id,Long placeId,PlaceRequest r){AacUser u=access.requireAccessibleUser(p,id);validate(r);SavedPlace x=placeId==null?places.save(SavedPlace.create(u,r.name(),r.placeType(),r.address(),r.latitude(),r.longitude(),r.radiusMeters(),r.activeFrom(),r.activeTo())):owned(u,placeId);if(placeId!=null)x.apply(r.name(),r.placeType(),r.address(),r.latitude(),r.longitude(),r.radiusMeters(),r.activeFrom(),r.activeTo());return PlaceResponse.from(x);}
 @Transactional public void delete(OidcUser p,Long id,Long placeId){AacUser u=access.requireAccessibleUser(p,id);owned(u,placeId).deactivate();}
 public LocationResponse latest(OidcUser p,Long id){access.requireAccessibleUser(p,id);return samples.findFirstByUserIdOrderByRecordedAtDesc(id).map(x->LocationResponse.from(x,List.of())).orElseThrow(()->new ResourceNotFoundException("위치 정보가 없습니다."));}
 public List<LocationResponse> history(OidcUser p,Long id,Instant from,Instant to){access.requireAccessibleUser(p,id);return samples.findAllByUserIdAndRecordedAtBetweenOrderByRecordedAtAsc(id,from,to).stream().map(x->LocationResponse.from(x,List.of())).toList();}
 @Transactional public LocationResponse record(AacDevice d,LocationRequest r){if(r.latitude()<-90||r.latitude()>90||r.longitude()<-180||r.longitude()>180)throw new BadRequestException("유효하지 않은 좌표입니다.");LocationSample s=samples.save(LocationSample.create(d,r.latitude(),r.longitude(),r.accuracyMeters(),r.recordedAt()));List<Long> outside=new ArrayList<>();LocalTime now=LocalTime.now();for(SavedPlace p:places.findAllByUserIdAndActiveTrueOrderByIdAsc(d.getUser().getId()))if(p.activeAt(now)&&distance(r.latitude(),r.longitude(),p.getLatitude(),p.getLongitude())>p.getRadiusMeters()){outside.add(p.getId());alerts.create(d.getUser(),AlertType.SAFE_ZONE_EXIT,"안심존 이탈",p.getName()+" 안심존을 벗어났습니다.");}live.publish(d.getUser().getId(),"LOCATION_UPDATED",Map.of("latitude",r.latitude(),"longitude",r.longitude(),"recordedAt",s.getRecordedAt().toString()));return LocationResponse.from(s,outside);}
 private SavedPlace owned(AacUser u,Long id){SavedPlace p=places.findById(id).orElseThrow(()->new ResourceNotFoundException("장소를 찾을 수 없습니다."));if(!p.getUser().getId().equals(u.getId()))throw new ForbiddenException("다른 사용자의 장소입니다.");return p;}private void validate(PlaceRequest r){if(r.name()==null||r.name().isBlank()||r.placeType()==null||r.radiusMeters()<10||r.radiusMeters()>10000)throw new BadRequestException("장소 이름, 유형, 반경(10~10000m)을 확인해주세요.");}private double distance(double a,double b,double c,double d){double R=6371000;double p1=Math.toRadians(a),p2=Math.toRadians(c),dp=Math.toRadians(c-a),dl=Math.toRadians(d-b);double x=Math.sin(dp/2)*Math.sin(dp/2)+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)*Math.sin(dl/2);return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
}
