CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(190) NOT NULL,
    name VARCHAR(80) NOT NULL,
    profile_image_url VARCHAR(500),
    account_type VARCHAR(30),
    onboarding_completed BOOLEAN NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_accounts_email UNIQUE (email)
);

CREATE TABLE oauth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    provider_email VARCHAR(190) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_oauth_account_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT uk_oauth_provider_subject UNIQUE (provider, provider_subject)
);

CREATE TABLE terms_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    terms_type VARCHAR(40) NOT NULL,
    terms_version VARCHAR(30) NOT NULL,
    agreed BOOLEAN NOT NULL,
    agreed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_terms_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT uk_terms_account_type_version UNIQUE (account_id, terms_type, terms_version)
);
