CREATE TABLE aac_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    mode VARCHAR(20) NOT NULL,
    grid_size VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE guardians (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(120) NOT NULL,
    phone VARCHAR(30),
    account_id BIGINT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_guardian_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT uk_guardian_email UNIQUE (email),
    CONSTRAINT uk_guardian_account UNIQUE (account_id)
);

CREATE TABLE user_guardians (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    guardian_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    primary_guardian BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_guardian_user FOREIGN KEY (user_id) REFERENCES aac_users (id),
    CONSTRAINT fk_user_guardian_guardian FOREIGN KEY (guardian_id) REFERENCES guardians (id),
    CONSTRAINT uk_user_guardian UNIQUE (user_id, guardian_id)
);

CREATE INDEX idx_user_guardians_guardian ON user_guardians (guardian_id);
