CREATE TABLE symbol_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_symbol_category_code UNIQUE (code)
);

CREATE TABLE symbols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    image_url VARCHAR(500),
    tts_text VARCHAR(200) NOT NULL,
    emergency BOOLEAN NOT NULL,
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_symbol_category FOREIGN KEY (category_id) REFERENCES symbol_categories (id)
);

CREATE TABLE user_favorite_symbols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    symbol_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES aac_users (id),
    CONSTRAINT fk_favorite_symbol FOREIGN KEY (symbol_id) REFERENCES symbols (id),
    CONSTRAINT uk_user_favorite_symbol UNIQUE (user_id, symbol_id)
);

CREATE TABLE symbol_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    symbol_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_usage_user FOREIGN KEY (user_id) REFERENCES aac_users (id),
    CONSTRAINT fk_usage_symbol FOREIGN KEY (symbol_id) REFERENCES symbols (id)
);

CREATE INDEX idx_usage_user_time ON symbol_usage_logs (user_id, occurred_at);
CREATE INDEX idx_usage_symbol ON symbol_usage_logs (symbol_id);
