ALTER TABLE aac_users ADD COLUMN birth_date DATE;
ALTER TABLE aac_users ADD COLUMN emergency_contact VARCHAR(30);
ALTER TABLE aac_users ADD COLUMN notes VARCHAR(1000);
ALTER TABLE aac_users ADD COLUMN profile_image_url VARCHAR(500);
ALTER TABLE aac_users ADD COLUMN voice_type VARCHAR(30) NOT NULL DEFAULT 'CHILD_MALE';
ALTER TABLE aac_users ADD COLUMN speech_rate NUMERIC(3,2) NOT NULL DEFAULT 1.00;
ALTER TABLE aac_users ADD COLUMN setup_step VARCHAR(30) NOT NULL DEFAULT 'PROFILE_COMPLETED';
ALTER TABLE aac_users ADD CONSTRAINT ck_aac_user_voice_type CHECK (voice_type IN ('CHILD_MALE','CHILD_FEMALE'));
ALTER TABLE aac_users ADD CONSTRAINT ck_aac_user_speech_rate CHECK (speech_rate >= 0.70 AND speech_rate <= 1.30);
ALTER TABLE aac_users ADD CONSTRAINT ck_aac_user_setup_step CHECK (setup_step IN ('PROFILE_COMPLETED','GRID_COMPLETED','VOICE_COMPLETED','CONFIRMED'));

ALTER TABLE user_guardians ADD COLUMN relationship_type VARCHAR(30);
ALTER TABLE user_guardians ADD COLUMN relationship_detail VARCHAR(100);
ALTER TABLE user_guardians ADD CONSTRAINT ck_user_guardian_relationship CHECK (relationship_type IS NULL OR relationship_type IN ('PARENT','GRANDPARENT','TEACHER','OTHER'));
ALTER TABLE user_guardians ADD CONSTRAINT ck_user_guardian_other_detail CHECK (relationship_type <> 'OTHER' OR LENGTH(TRIM(relationship_detail)) > 0);

CREATE TABLE aac_devices (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 device_id VARCHAR(100) NOT NULL,
 device_name VARCHAR(100),
 device_type VARCHAR(20) NOT NULL,
 status VARCHAR(20) NOT NULL,
 paired_at TIMESTAMP WITH TIME ZONE NOT NULL,
 last_seen_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_aac_device_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id),
 CONSTRAINT uk_aac_device_device_id UNIQUE(device_id),
 CONSTRAINT ck_aac_device_type CHECK (device_type IN ('TABLET','MOBILE','WEB','UNKNOWN')),
 CONSTRAINT ck_aac_device_status CHECK (status IN ('ACTIVE','REVOKED'))
);
CREATE INDEX idx_aac_devices_user ON aac_devices(aac_user_id);

CREATE TABLE device_pairing_sessions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 guardian_id BIGINT NOT NULL,
 qr_token_hash VARCHAR(64) NOT NULL,
 invite_code_hash VARCHAR(64) NOT NULL,
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
 used_at TIMESTAMP WITH TIME ZONE,
 revoked_at TIMESTAMP WITH TIME ZONE,
 status VARCHAR(20) NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_pairing_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id),
 CONSTRAINT fk_pairing_guardian FOREIGN KEY (guardian_id) REFERENCES guardians(id),
 CONSTRAINT uk_pairing_qr_hash UNIQUE(qr_token_hash),
 CONSTRAINT uk_pairing_code_hash UNIQUE(invite_code_hash),
 CONSTRAINT ck_pairing_status CHECK (status IN ('ACTIVE','USED','EXPIRED','REVOKED'))
);
CREATE INDEX idx_pairing_user_status ON device_pairing_sessions(aac_user_id,status);
CREATE INDEX idx_pairing_expires ON device_pairing_sessions(expires_at);
CREATE INDEX idx_pairing_guardian ON device_pairing_sessions(guardian_id);
