ALTER TABLE guardians ADD COLUMN tutorial_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE guardians ADD COLUMN tutorial_completed_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE aac_users ADD COLUMN sentence_level INTEGER NOT NULL DEFAULT 2;
ALTER TABLE aac_users ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'STABLE';
ALTER TABLE aac_users ADD COLUMN board_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE aac_users ADD CONSTRAINT ck_aac_user_sentence_level CHECK (sentence_level BETWEEN 1 AND 4);
ALTER TABLE aac_users ADD CONSTRAINT ck_aac_user_status CHECK (status IN ('STABLE','EMERGENCY'));
ALTER TABLE aac_users DROP CONSTRAINT ck_aac_user_voice_type;
ALTER TABLE aac_users ADD CONSTRAINT ck_aac_user_voice_type CHECK (voice_type IN ('CHILD_MALE','CHILD_FEMALE','ADULT_FEMALE','ADULT_MALE'));

CREATE TABLE board_categories (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 name VARCHAR(50) NOT NULL,
 color VARCHAR(20),
 display_order INTEGER NOT NULL,
 active BOOLEAN NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_board_category_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id)
);
CREATE INDEX idx_board_category_user ON board_categories(aac_user_id,active,display_order);

CREATE TABLE aac_cards (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 category_id BIGINT NOT NULL,
 text VARCHAR(80) NOT NULL,
 image_url VARCHAR(500),
 tts_text VARCHAR(200) NOT NULL,
 emergency BOOLEAN NOT NULL,
 favorite BOOLEAN NOT NULL,
 display_order INTEGER NOT NULL,
 active BOOLEAN NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_aac_card_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id),
 CONSTRAINT fk_aac_card_category FOREIGN KEY (category_id) REFERENCES board_categories(id)
);
CREATE INDEX idx_aac_card_user ON aac_cards(aac_user_id,active,display_order);

CREATE TABLE card_usage_logs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 card_id BIGINT NOT NULL,
 action VARCHAR(20) NOT NULL,
 occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_card_usage_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id),
 CONSTRAINT fk_card_usage_card FOREIGN KEY (card_id) REFERENCES aac_cards(id)
);
CREATE INDEX idx_card_usage_user_time ON card_usage_logs(aac_user_id,occurred_at);

CREATE TABLE device_access_tokens (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 device_id BIGINT NOT NULL,
 token_hash VARCHAR(64) NOT NULL,
 expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
 revoked_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_device_token_device FOREIGN KEY (device_id) REFERENCES aac_devices(id),
 CONSTRAINT uk_device_token_hash UNIQUE(token_hash)
);
CREATE INDEX idx_device_token_device ON device_access_tokens(device_id);

CREATE TABLE saved_places (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 name VARCHAR(80) NOT NULL,
 place_type VARCHAR(30) NOT NULL,
 address VARCHAR(300),
 latitude DOUBLE PRECISION NOT NULL,
 longitude DOUBLE PRECISION NOT NULL,
 radius_meters INTEGER NOT NULL,
 active_from TIME,
 active_to TIME,
 active BOOLEAN NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_saved_place_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id)
);

CREATE TABLE location_samples (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 device_id BIGINT NOT NULL,
 latitude DOUBLE PRECISION NOT NULL,
 longitude DOUBLE PRECISION NOT NULL,
 accuracy_meters DOUBLE PRECISION,
 recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_location_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id),
 CONSTRAINT fk_location_device FOREIGN KEY (device_id) REFERENCES aac_devices(id)
);
CREATE INDEX idx_location_user_time ON location_samples(aac_user_id,recorded_at);

CREATE TABLE routines (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 title VARCHAR(100) NOT NULL,
 message VARCHAR(300) NOT NULL,
 time_of_day TIME NOT NULL,
 days_of_week VARCHAR(40) NOT NULL,
 timezone VARCHAR(50) NOT NULL,
 enabled BOOLEAN NOT NULL,
 last_triggered_date DATE,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_routine_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id)
);

CREATE TABLE sensor_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 device_id BIGINT,
 event_type VARCHAR(30) NOT NULL,
 numeric_value DOUBLE PRECISION,
 label VARCHAR(100),
 recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_sensor_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id),
 CONSTRAINT fk_sensor_device FOREIGN KEY (device_id) REFERENCES aac_devices(id)
);
CREATE INDEX idx_sensor_user_time ON sensor_events(aac_user_id,recorded_at);

CREATE TABLE notification_subscriptions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 guardian_id BIGINT NOT NULL,
 endpoint VARCHAR(1000) NOT NULL,
 p256dh VARCHAR(300) NOT NULL,
 auth_key VARCHAR(300) NOT NULL,
 active BOOLEAN NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_subscription_guardian FOREIGN KEY (guardian_id) REFERENCES guardians(id),
 CONSTRAINT uk_subscription_endpoint UNIQUE(endpoint)
);

CREATE TABLE alert_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 alert_type VARCHAR(30) NOT NULL,
 title VARCHAR(120) NOT NULL,
 message VARCHAR(500) NOT NULL,
 occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
 acknowledged_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_alert_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id)
);
CREATE INDEX idx_alert_user_time ON alert_events(aac_user_id,occurred_at);
