ALTER TABLE guardians ADD COLUMN push_token VARCHAR(255);

CREATE TABLE guardian_notifications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 guardian_id BIGINT NOT NULL,
 aac_user_id BIGINT NOT NULL,
 symbol_id BIGINT,
 message VARCHAR(200) NOT NULL,
 read BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_guardian_notification_guardian FOREIGN KEY (guardian_id) REFERENCES guardians(id),
 CONSTRAINT fk_guardian_notification_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id),
 CONSTRAINT fk_guardian_notification_symbol FOREIGN KEY (symbol_id) REFERENCES symbols(id)
);
CREATE INDEX idx_guardian_notification_guardian ON guardian_notifications(guardian_id, created_at);
