ALTER TABLE aac_users ADD COLUMN max_recommended_sentence_words INTEGER NOT NULL DEFAULT 4;
ALTER TABLE aac_users ADD COLUMN easy_words_preferred BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE aac_users ADD COLUMN abstract_expressions_restricted BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE aac_users ADD COLUMN complex_grammar_restricted BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE aac_users ADD COLUMN concise_direct_preferred BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE aac_users ADD CONSTRAINT ck_aac_user_max_sentence_words
    CHECK (max_recommended_sentence_words BETWEEN 1 AND 30);

ALTER TABLE aac_cards ALTER COLUMN tts_text DROP NOT NULL;
UPDATE aac_cards SET tts_text = NULL WHERE tts_text = text;
ALTER TABLE aac_cards ADD COLUMN image_source_type VARCHAR(30) NOT NULL DEFAULT 'SYSTEM_DEFAULT';
ALTER TABLE aac_cards ADD COLUMN image_source_name VARCHAR(120);
ALTER TABLE aac_cards ADD COLUMN image_license VARCHAR(120);
ALTER TABLE aac_cards ADD COLUMN image_attribution_url VARCHAR(500);
ALTER TABLE aac_cards ADD COLUMN important BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE aac_cards ADD COLUMN system_card BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE aac_cards ADD CONSTRAINT ck_aac_card_image_source_type
    CHECK (image_source_type IN ('SYSTEM_DEFAULT', 'USER_UPLOAD', 'EXTERNAL_ALLOWED'));

ALTER TABLE card_usage_logs ALTER COLUMN card_id DROP NOT NULL;
ALTER TABLE card_usage_logs ADD COLUMN device_id BIGINT;
ALTER TABLE card_usage_logs ADD COLUMN display_text_snapshot VARCHAR(80);
ALTER TABLE card_usage_logs ADD COLUMN spoken_text VARCHAR(500);
ALTER TABLE card_usage_logs ADD CONSTRAINT fk_card_usage_device
    FOREIGN KEY (device_id) REFERENCES aac_devices(id);
CREATE INDEX idx_card_usage_device ON card_usage_logs(device_id);
UPDATE card_usage_logs
SET display_text_snapshot = (SELECT c.text FROM aac_cards c WHERE c.id = card_usage_logs.card_id);

CREATE TABLE stt_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 aac_user_id BIGINT NOT NULL,
 device_id BIGINT NOT NULL,
 recognized_text VARCHAR(2000),
 successful BOOLEAN NOT NULL,
 confidence DOUBLE PRECISION,
 recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
 created_at TIMESTAMP(6) NOT NULL,
 updated_at TIMESTAMP(6) NOT NULL,
 CONSTRAINT fk_stt_event_user FOREIGN KEY (aac_user_id) REFERENCES aac_users(id),
 CONSTRAINT fk_stt_event_device FOREIGN KEY (device_id) REFERENCES aac_devices(id),
 CONSTRAINT ck_stt_event_confidence CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
 CONSTRAINT ck_stt_event_success_text CHECK (
     successful = FALSE OR (recognized_text IS NOT NULL AND LENGTH(TRIM(recognized_text)) > 0)
 )
);
CREATE INDEX idx_stt_event_user_time ON stt_events(aac_user_id, recorded_at);
CREATE INDEX idx_stt_event_device ON stt_events(device_id);
